name: Kubernetes Health Check
description: Wait for and verify pod readiness in Kubernetes

inputs:
  app_label_selector:
    description: Kubernetes label selector for app pods
    required: true
  timeout:
    description: Wait timeout for pod readiness
    required: false
    default: '300s'

runs:
  using: composite
  steps:
    - name: Wait for pods to be ready
      shell: bash
      run: |
        kubectl wait --for=condition=ready pod -l app=${{ inputs.app_label_selector }} \
          -n monitoring --timeout=120s

    - name: Health check
      shell: bash
      run: |
        echo "=== Health check ==="
        # Check if all pods are running
        READY_PODS=$(kubectl get pods -n monitoring -l app=${{ inputs.app_label_selector }} \
          -o jsonpath='{.items[*].status.phase}' | grep -o Running | wc -l)
        TOTAL_PODS=$(kubectl get pods -n monitoring \
          -l app=${{ inputs.app_label_selector }} --no-headers | wc -l)
        echo "Ready pods: $READY_PODS / $TOTAL_PODS"
        if [ "$READY_PODS" -eq "$TOTAL_PODS" ] && \
           [ "$TOTAL_PODS" -gt 0 ]; then
          echo "✅ All pods are running successfully"
        else
          echo "❌ Not all pods are running"
          kubectl describe pods -n monitoring -l app=${{ inputs.app_label_selector }}
          kubectl logs -n monitoring -l app=${{ inputs.app_label_selector }} --tail=50
          exit 1
        fi
