name: Setup Minikube
description: Setup Minikube cluster with consistent configuration for testing

runs:
  using: composite
  steps:
    - name: Setup Minikube with 2 nodes
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        driver: docker
        container-runtime: docker
        kubernetes-version: v1.32.0
        cpus: 2
        memory: 2048m
        addons: metrics-server
        start-args: '--nodes=2'

    - name: Verify Minikube cluster
      shell: bash
      run: |
        kubectl cluster-info
        kubectl get nodes
