name: Deploy Helm Chart
description: Deploy application using Helm with consistent configuration

inputs:
  chart_path:
    description: Path to Helm chart
    required: true
  release_name:
    description: Helm release name
    required: true
  app_name:
    description: Application name
    required: true

runs:
  using: composite
  steps:
    - name: Create monitoring namespace
      shell: bash
      run: |
        kubectl create namespace monitoring || true

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Deploy application with Helm
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.release_name }} ${{ inputs.chart_path }} \
          --namespace monitoring \
          --set image.tag=test \
          --set image.repository=${{ inputs.app_name }} \
          --set image.pullPolicy=Never \
          --set serviceMonitor.enabled=false \
          --wait --timeout=300s

    - name: Verify deployment
      shell: bash
      run: |
        echo "=== Checking deployment status ==="
        kubectl get pods -n monitoring
        kubectl get services -n monitoring
        kubectl get configmap -n monitoring
