name: Check Code Changes
description: Check if code files have changed to determine if build is needed

inputs:
  file_patterns:
    description: Regex pattern for language-specific files to check (e.g., '\.(go|mod|sum)$|Dockerfile|^(src|cmd)/')
    required: true
  event_name:
    description: GitHub event name
    required: true
  detect_workflow_changes:
    description: Also detect workflow file changes
    required: false
    default: 'false'

outputs:
  code-changed:
    description: Whether code changes were detected
    value: ${{ steps.changes.outputs.code }}
  workflow-changed:
    description: Whether workflow files changed (only if detect_workflow_changes is true)
    value: ${{ steps.changes.outputs.workflow }}

runs:
  using: composite
  steps:
    - name: Check for code changes
      id: changes
      shell: bash
      run: |
        if [ "${{ inputs.event_name }}" = "release" ]; then
          echo "Release event - forcing build"
          echo "code=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # For workflow_dispatch, always build
        if [ "${{ inputs.event_name }}" = "workflow_dispatch" ]; then
          echo "Manual workflow dispatch - forcing build"
          echo "code=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # For push events, check if there are changes to code files
        if [ "${{ inputs.event_name }}" = "push" ]; then
          # Check if previous commit exists
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            # Check for changes in language-specific files
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

            # Look for changes matching the file pattern
            if echo "$CHANGED_FILES" | grep -E '${{ inputs.file_patterns }}' > /dev/null; then
              echo "Code changes detected:"
              echo "$CHANGED_FILES" | grep -E '${{ inputs.file_patterns }}'
              echo "code=true" >> $GITHUB_OUTPUT
            else
              echo "No code changes detected. Only documentation/config changes:"
              echo "$CHANGED_FILES"
              echo "code=false" >> $GITHUB_OUTPUT
            fi

            # Check for workflow changes if requested
            if [ "${{ inputs.detect_workflow_changes }}" = "true" ]; then
              if echo "$CHANGED_FILES" | grep -E '\.github/workflows/' > /dev/null; then
                echo "Workflow changes detected"
                echo "workflow=true" >> $GITHUB_OUTPUT
              else
                echo "workflow=false" >> $GITHUB_OUTPUT
              fi
            fi
          else
            echo "First commit - forcing build"
            echo "code=true" >> $GITHUB_OUTPUT
          fi
        else
          # For PR events, always run tests but don't push
          echo "Pull request - running tests only"
          echo "code=false" >> $GITHUB_OUTPUT
        fi
